CREATE TABLE freeboard (
	CODE_TYPE VARCHAR2(2),
	NUM NUMBER(5) NOT NULL,
	NAME VARCHAR2(100BYTE),
	TITLE VARCHAR2(100BYTE),
	CONTENT VARCHAR2(100BYTE),
	REGDATE DATE DEFAULT SYSDATE,
	CONSTRAINT num_pk PRIMARY KEY (NUM)
);

TRUNCATE TABLE FREEBOARD ;
DROP SEQUENCE FREEBOARDNUM_SEQ;
DROP TABLE FREEBOARD ;

CREATE SEQUENCE FREEBOARDNUM_SEQ
	INCREMENT BY 1
	START WITH 1
	MINVALUE 1
	MAXVALUE 9999
	NOCYCLE
	NOCACHE
	ORDER;

INSERT INTO FREEBOARD(CODE_TYPE,NUM,NAME,TITLE,CONTENT,REGDATE)
VALUES ('01',FREEBOARDNUM_SEQ.NEXTVAL,'±³À°»ý1','¾È³çÇÏ¼¼¿ä','¾È³çÇÏ¼¼¿ä','2020/09/14');
INSERT INTO FREEBOARD(CODE_TYPE,NUM,NAME,TITLE,CONTENT,REGDATE)
VALUES ('02',FREEBOARDNUM_SEQ.NEXTVAL,'±³À°»ý2','¸ðµÎ ¾È³ç','ÀßºÎÅ¹ÇØ','2020/10/03');
INSERT INTO FREEBOARD(CODE_TYPE,NUM,NAME,TITLE,CONTENT,REGDATE)
VALUES ('03',FREEBOARDNUM_SEQ.NEXTVAL,'±³À°»ý3','Çï·Î','ÇÏÀÌÇÏÀÌ','2020/10/29');
INSERT INTO FREEBOARD(CODE_TYPE,NUM,NAME,TITLE,CONTENT,REGDATE)
VALUES ('01',FREEBOARDNUM_SEQ.NEXTVAL,'±³À°»ý4','Hi, Everyone','Nice to meet you guys','2020/11/18');
INSERT INTO FREEBOARD(CODE_TYPE,NUM,NAME,TITLE,CONTENT,REGDATE)
VALUES ('02',FREEBOARDNUM_SEQ.NEXTVAL,'±³À°»ý5','¾È³çÇÏ¼¼¿ä','ÀßºÎÅ¹µå¸³´Ï´Ù ±è¶¯¶¯ÀÔ´Ï´Ù.','2020/12/27');

SELECT CASE WHEN CODE_TYPE = '01' THEN 'ÀÚÀ¯' 
					WHEN CODE_TYPE = '02' THEN 'ÀÍ¸í'
					WHEN CODE_TYPE = '03' THEN 'QnA'
					ELSE NULL
					END AS CODE_TYPE,
				ROW_NUMBER() OVER(ORDER BY NUM) AS ROW_NUM, NAME, TITLE, CONTENT, TO_CHAR(REGDATE , 'YYYY/MM/DD') AS REGDATE 
				FROM FREEBOARD ORDER BY NUM;

SELECT NUM, TITLE, NAME, TO_CHAR(REGDATE,'YYYY/MM/DD') REGDATE, CONTENT FROM FREEBOARD
		WHERE NUM= 22;
		
SELECT CASE WHEN CODE_TYPE = '01' THEN 'ÀÚÀ¯' 
					WHEN CODE_TYPE = '02' THEN 'ÀÍ¸í'
					WHEN CODE_TYPE = '03' THEN 'QnA'
					ELSE NULL
					END AS CODE_TYPE,
	NUM, NAME, TITLE, CONTENT, TO_CHAR(REGDATE , 'YYYY/MM/DD') AS REGDATE FROM FREEBOARD ORDER BY NUM ;
	

SELECT FREEBOARDNUM_SEQ.CURRVAL FROM FREEBOARD;

SELECT FREEBOARDNUM_SEQ.NEXTVAL FROM DUAL;

DELETE FROM FREEBOARD WHERE NUM IN ( 4 , 5 );